/*
 Prompts user for conversion type and value to be converted,
converts given value to selected unit of measurement.
May 17, 2017
Brett Castellano
 */

/**
 *
 * @author brcas1396
 */
import java.text.DecimalFormat;

public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        option1 = new javax.swing.JLabel();
        option2 = new javax.swing.JLabel();
        option3 = new javax.swing.JLabel();
        option4 = new javax.swing.JLabel();
        option5 = new javax.swing.JLabel();
        choiceValue = new javax.swing.JTextField();
        valueInput = new javax.swing.JTextField();
        choicePrompt = new javax.swing.JLabel();
        valuePrompt = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        finalSentence = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("SerifaDEE", 1, 24)); // NOI18N
        Title.setText("Linear Conversion");

        option1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option1.setText("1. Inches to Centimetres");

        option2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option2.setText("2. Feet to Centimetres ");

        option3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option3.setText("3. Pints to Litres ");

        option4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option4.setText("4. Miles to Kilometres");

        option5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option5.setText("5. Stones to Kilograms ");

        choicePrompt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        choicePrompt.setText("Enter conversion choice (1-5)");

        valuePrompt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valuePrompt.setText("Enter value to be converted: ");

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        finalSentence.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        finalSentence.setForeground(new java.awt.Color(0, 51, 255));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Quit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Help");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option4)
                                    .addComponent(option3)
                                    .addComponent(option2)
                                    .addComponent(option1)
                                    .addComponent(option5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valuePrompt)
                                    .addComponent(choicePrompt))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valueInput, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(choiceValue)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Title)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(finalSentence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(option1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choicePrompt)
                    .addComponent(choiceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valuePrompt)
                    .addComponent(valueInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(convertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finalSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * close the program
     * pre: none
     * post: closed program
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * converts given value from inches to centimetres
     * pre: value in inches
     * post: value in centimetres
     */
    public static double inchesToCentimetres(double value) {
        value *= 2.54;
        return value;
    }
    /**
     *converts given value from feet to centimetres
     * pre: value in feet
     * post: value in centimetres
     */
    public static double feetToCentimetres(double value) {
        value *= 30.48;
        return value;
    }
    /**
     *converts given value from pints to litres
     * pre: value in pints
     * post: value in litres
     */
    public static double pintsToLitres(double value) {
        value *= 0.47;
        return value;
    }
    /**
     *converts given value from miles to kilometres
     * pre: value in miles
     * post: value in kilometres
     */
    public static double milesToKilometres(double value) {
        value *= 1.6;
        return value;
    }
    /**
     *converts given value from stones to kilograms
     * pre: value in stones
     * post: value in kilograms
     */
    public static double stonesToKilograms(double value) {
        value *= 6.35;
        return value;
    }
    /**
     * receives conversion method from user,
     * converts user's value using chosen method
     * pre: method humber > 0 and <  5, value to be converted
     * post: value converted to desired unit,
     * in sentence form, to two decimal places
     */
    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
       
        /* declare all variables */
        int choice;
        double value, value2;
        DecimalFormat x = new DecimalFormat("###.00");      //two decimal places

        /*get conversion method and value from user */
        choice = Integer.parseInt(choiceValue.getText());
        value = Double.parseDouble(valueInput.getText());

        /* only five choices */
        if (choice < 1 || choice > 5) {
            finalSentence.setText("Not a valid number");
        }
        
        /* run method based on conversion chosen by user */
        switch (choice) {
            case 1:
                value2 = inchesToCentimetres(value);        //value returned after conversion
                finalSentence.setText((x.format(value)) + " Inches = " + (x.format(value2)) + " Centimetres");
                break;
            case 2:
                value2 = feetToCentimetres(value);
                finalSentence.setText((x.format(value)) + " Feet = " + (x.format(value2)) + " Centimetres");
                break;
            case 3:
                value2 = pintsToLitres(value);
                finalSentence.setText((x.format(value)) + " Pints = " + (x.format(value2)) + " Litres");
                break;
            case 4:
                value2 = milesToKilometres(value);
                finalSentence.setText((x.format(value)) + " Miles = " + (x.format(value2)) + " Kilometres");
                break;
            case 5:
                value2 = stonesToKilograms(value);
                finalSentence.setText((x.format(value)) + " Stones = " + (x.format(value2)) + " Kilograms");
                break;
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel choicePrompt;
    private javax.swing.JTextField choiceValue;
    private javax.swing.JButton convertButton;
    private javax.swing.JLabel finalSentence;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel option1;
    private javax.swing.JLabel option2;
    private javax.swing.JLabel option3;
    private javax.swing.JLabel option4;
    private javax.swing.JLabel option5;
    private javax.swing.JTextField valueInput;
    private javax.swing.JLabel valuePrompt;
    // End of variables declaration//GEN-END:variables
}
